version: '3.4'

services:
  postgres-server:
    image: postgres:13.8
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix_pwd
      - POSTGRES_DB=zabbix
    restart: unless-stopped
    volumes:
      - /volume1/docker/Zabbix/database:/var/lib/postgresql/data

  zabbix-server-pgsql:
    image: zabbix/zabbix-server-pgsql:alpine-6.0-latest
    environment:
      - DB_SERVER_HOST=postgres-server
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix_pwd
      - POSTGRES_DB=zabbix
    ports:
      - 10051:10051
    restart: unless-stopped

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.0-latest
    environment:
      - ZBX_SERVER_HOST=zabbix-server-pgsql
      - DB_SERVER_HOST=postgres-server
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=zabbix_pwd
      - POSTGRES_DB=zabbix
    ports:
        - 9999:8443
        - 9080:8080
    restart: unless-stopped
